### ISSUE TITLE
Paraiso themes are not working

### ISSUE THREAD

**Issue by noresjo** [gerane/VSCodeThemes#1]
I'm not sure but I believe the Paraiso themes are not working. I haven't tried the other ones. The obvious issue for me is that the background color is incorrect when using paraiso_dark. Does it work for you @gerane ?

<img width="317" alt="screen shot 2015-11-27 at 10 54 06" src="https://cloud.githubusercontent.com/assets/5551926/11438447/4157e0c4-94f5-11e5-92f7-62f169254552.png">

I'm on a mac, running CODE Version 0.10.1 (0.10.1)

**Comment by noresjo** [comment]
Same in windows.

**Comment by gerane** [comment]
Yeah, they both seem off for me. I ported theme directly from the themes on ColorSublime.com

I will have to do a little digging to figure out why they aren't properly working.

**Comment by gerane** [comment]
These should be working now. I also added icons and screenshots.
