### ISSUE TITLE
Theme-Dreamweaver is not working

### ISSUE THREAD

**Issue by g30225579** [gerane/VSCodeThemes#13]
It's not working and no effect. 

I'm on windows 10, vscode version is 1.0.

**Comment by gerane** [comment]
There was something wrong with the tmtheme, I just fixed this issue and added an icon and screenshot.

**Comment by g30225579** [comment]
Thanks.  I'd like to set like this, is ok ?
![css](https://cloud.githubusercontent.com/assets/17231597/14915798/31dccf70-0e48-11e6-9816-24403d6e4de5.png)
![js](https://cloud.githubusercontent.com/assets/17231597/14915799/31e262d2-0e48-11e6-911d-3c7ecf35354f.png)
![php](https://cloud.githubusercontent.com/assets/17231597/14915800/31e34b7a-0e48-11e6-8bfc-6d339d1967d7.png)
