### ISSUE TITLE
[Tomorrow_Night] HTML highlighting is not good at all

### ISSUE THREAD

**Issue by glen-84** [gerane/VSCodeThemes#14]
Compare this: http://colorsublime.com/theme/Tomorrow_Night (Html tab)

With this (from VS Code):

![tom-night](https://cloud.githubusercontent.com/assets/261509/14942244/fcfc4cfc-0fb6-11e6-9101-e359984db2cc.png)

**Comment by gerane** [comment]
What version of the theme are you using? I am not seeing this issue. When I apply the theme it looks like the one on colorsublime.

Can you install the Tomorrow theme pack by microsoft and see if it has a similar issue? I see the proper colors using both versions.

**Comment by glen-84** [comment]
Arrrghh, it was caused by [this](https://marketplace.visualstudio.com/items?itemName=bajdzis.vscode-twig-pack) extension.

Sorry for wasting your time! :worried:
