### ISSUE TITLE
Capo Light : Some foreground items difficult to read

### ISSUE THREAD

**Issue by savioret** [gerane/VSCodeThemes#15]
First of all, I find this theme great, it's difficult to find good light themes like this.
I'm using version 1.1.0 (recently upgraded from 1.0)
Attached an image sample of 3 problems that I find quite annoying to work with.

1.  The current file path should be darker to be readable
2. When searching a string in the current editor, the text of the search box is not visible ("Monaco" should be read in the example image). 
Also the "No results" tag next to this search text box when no matches, has a dark grey foreground difficult to read over the dark red background.
3. In json files, "comma" and "colon" and "semicolon" are barely visible.

![capo_theme](https://cloud.githubusercontent.com/assets/5497332/15246800/8ca09e9a-1907-11e6-961a-28b20568e8b6.png)

I tried to figure out how to modify the theme but I couldn't locate the exact tags.
I hope they could be fixed.

Thanks !!

**Comment by gerane** [comment]
Thanks for bringing this to my attention. I will try to look at this in the morning.

**Comment by rbatukaev** [comment]
The cursor is barely visible as well

**Comment by gerane** [comment]
I will look at this soon. I have had less free time for non work projects than expected lately.
