### ISSUE TITLE
Batman: Java Comments not visible on inactive lines

### ISSUE THREAD

**Issue by kaivalya97** [gerane/VSCodeThemes#16]
The Batman theme is one of the best I have ever used on Visual Studio Code. However, there is a slight issue due to the color scheme of the comments in Java and inactive lines.

As you can see in the screenshots below, both the lines contain comments but a comment is only visible when the cursor is on the same line.

Kindly solve this at the earliest. In the meanwhile, I'll have to switch to another theme as I primarily use Java and need to read comments on multiple lines at the same time.

![1](https://cloud.githubusercontent.com/assets/18525022/15584732/7c021b4e-2399-11e6-95f6-a36f39fd7103.JPG)
![2](https://cloud.githubusercontent.com/assets/18525022/15584733/7c4b6556-2399-11e6-8f1f-b3c476d232bb.JPG)

**Comment by gerane** [comment]
Thanks, I will look at this in the morning a see if I can make this a bit more legible.
