### ISSUE TITLE
Add screenshots?

### ISSUE THREAD

**Issue by eliashdezr** [gerane/VSCodeThemes#2]
Since you the theme gallery is flooded by yours, can you add at least images to preview the themes?

**Comment by gerane** [comment]
They didn't have proper screenshot support in the gallery when I scripted the creation of these Themes. There were only a handful of themes in the Gallery at the time, and I based my Template on these off the Themes Microsoft created. I will try to to make some time to go back and look into this.

Also, anyone who has screenshots of any of these themes feel free to make a pull request.

**Comment by stylemistake** [comment]
> feel free to make a pull request.

You don't seem to care about 5 pending pull requests in your repo, apparently. :+1:

**Comment by eliashdezr** [comment]
@gerane you can pass the repo to another user that actually can take care of.

**Comment by gerane** [comment]
I will try to have those pushed to the gallery in the morning. I am also trying to make some time to go through the themes I have published and get screenshots created for them and weed out the ones that did not properly port over.

**Comment by gerane** [comment]
I am working on adding icons and screenshots to all of my themes currently. I will update them on the Marketplace as I go.

**Comment by gerane** [comment]
I have added icons and screenshots to all of my themes. I have also gone through and fixed a lot of broken themes or properly labeled ones.
