### ISSUE TITLE
Birds of Paradise Not Working

### ISSUE THREAD

**Issue by bcrotty** [gerane/VSCodeThemes#3]
I installed VSCode fresh today and tried to install Birds of Paradise, but it reverted back to the default theme when I switched to it. Reinstalling Birds of Paradise didn't work. Anything else I should try? Thanks!

**Comment by gerane** [comment]
Yeah, I saw the same thing. I ported this from an existing theme on colorsublime.com. I will need to try to check and figure out if the theme I ported was actually working or not. 

At first glance, what I am seeing in this theme is the tmTheme file I ported this theme from has some odd unicode characters in it that VSCode might not be able to handle.

**Comment by gerane** [comment]
I just pushed a fix for this theme and added screenshot and icon
