### ISSUE TITLE
Credit please :)

### ISSUE THREAD

**Issue by stagfoo** [gerane/VSCodeThemes#30]
Hey buddy,
firstly thanks for porting my theme, very handy now that I have moved to vs code. Could you add my name to the read me please though  👼  its the `Meteor Theme`

**Comment by gerane** [comment]
Not a problem at all. Any preferred way you'd like me to credit you?

**Comment by stagfoo** [comment]
Just a tiny link, :smile: feel free to assign me to any bugs with the theme im always happy to help out

**Comment by gerane** [comment]
Sounds good. Should be able to look at this later tonight.

**Comment by gerane** [comment]
Merged and Published
