### ISSUE TITLE
Monokai-Soft doesnt support markdown

### ISSUE THREAD

**Issue by amandaporto** [gerane/VSCodeThemes#34]
Right now, the Monokai-Soft theme doesnt support markdown. It would be nice to have syntax highlighting for markdown files as well (different colors for different headers, bold, italic, etc). 

![atom-notes_md_-_webapp](https://cloud.githubusercontent.com/assets/12819656/23525841/d9e579d6-ff5d-11e6-87e3-37202dbc194a.png)

**Comment by gerane** [comment]
@amandaporto I will try to get the markdown back for this one. When they changed their markdown engine a long while ago, it broke the scoping of several themes. I haven't had a chance to go through and track them all down.
