### ISSUE TITLE
Theme Request - Glacier

### ISSUE THREAD

**Issue by bcrotty** [gerane/VSCodeThemes#4]
Thanks so much for porting all of these themes! Would it be possible to get [Materialize - Glacier](https://packagecontrol.io/packages/Materialize) or [Glacier](https://packagecontrol.io/packages/Theme%20-%20Glacier)?

**Comment by gerane** [comment]
If you have access to the tmTheme file, you can port it to VSCode. The below link has information about it.

https://code.visualstudio.com/docs/tools/yocode

I have been really busy with some projects at work and have not had the time to work on anything VSCode related. I could eventually try to port this when I have more time, but I am currently unsure when that might be. Right now a higher priority for my free time would be correcting or removing any themes that are broken and working towards getting Screenshots up and available for each theme.
