### ISSUE TITLE
Highlight using wrong colors for Solarized Light Theme

### ISSUE THREAD

**Issue by felipecrp** [gerane/VSCodeThemes#41]
This is a sample code, in which the cursor is on "abc" string.

In vscode 1.7.2, it use the right colors:

![old](https://cloud.githubusercontent.com/assets/615155/25094108/f8d959b6-236b-11e7-8b52-9a234a359604.png)

But in vscode 1.11.2, it use the same (or near same) color of selection:

![new](https://cloud.githubusercontent.com/assets/615155/25094117/0434f0b8-236c-11e7-8e94-0f9a1d5065ad.png)

**Comment by gerane** [comment]
I'm not quite sure what they changed. I did see one issue with this theme that I will be fixing, but it wasn't related to this. I will have to look into this a bit more. Was 1.7.2 the latest version you had tried before 1.11.2? I am wondering at what point this started happening.

**Comment by felipecrp** [comment]
Yes, i updated from 1.7.2 to 1.11.1, and after 1.11.2. The wrong highlight happens in 1.11.1 and 1.11.2.

**Comment by felipecrp** [comment]
Read the change logs, it may be the update from version 1.9 or 1.11

https://code.visualstudio.com/updates/v1_9 - they changed something in themes to be more accurate with textmate

https://code.visualstudio.com/updates/v1_11 - they launched new features for themes

**Comment by felipecrp** [comment]
Can you tell what is the "theme tag" for highlight repeated ocurrences and selection?

**Comment by gerane** [comment]
Sorry for the delay. I've been sick and daughters been sick. Even missed a conference over the weekend. I'll try to check into this sometime today. It looks like part of it is working as intended now, but something is still clashing. The foreground color should be lighter and the background color is actually showing more the way it should be. I'll try to see of I can find a good mix to make everything look proper.

**Comment by gerane** [comment]
Ok. I made a change that should make this a lot better and fixed an issue with it being defined as a dark theme. I think there should eventually be some better ways to customize these, but right now it doesn't look like it works for tmtheme. This may be something that only works in their newer json format. I am waiting until that is more finalized before I start moving themes to it.
