### ISSUE TITLE
FocusDark do not seems to work as expected

### ISSUE THREAD

**Issue by bbenoist** [gerane/VSCodeThemes#5]
[Expected](http://colorsublime.com/theme/Focus_Dark):

![image](https://cloud.githubusercontent.com/assets/2091902/13324171/ce61daaa-dbdc-11e5-8cc8-99ff702e5a43.png)

Actual:

![image](https://cloud.githubusercontent.com/assets/2091902/13324222/f898f560-dbdc-11e5-900a-0b7983f8ea8b.png)

**Comment by gerane** [comment]
I will try to make some time to look at this. I want to see if I can figure out any patterns in the themes that don't properly get ported. I know one of the ones I was looking at in another issue had odd unicode characters in it and I wasn't sure if that was causing the themes to improperly port or not.

**Comment by gerane** [comment]
I just pushed a fix for this and added an icon and screenshot.

**Comment by bbenoist** [comment]
:+1: Thanks for the work
