### ISSUE TITLE
Add references to the GitHub repository in README.md and package.json files

### ISSUE THREAD

**Issue by bbenoist** [gerane/VSCodeThemes#6]
I got lucky to find your username on GitHub but other people might not have the same reflex.

See https://code.visualstudio.com/docs/extensionAPI/extension-manifest for more info on the package,json part.

**Comment by gerane** [comment]
The Package.json part for homepage and repo should all be there. On the Gallery, there is a side column called resources that link to the github repo and github homepage readme. There weren't many examples when I originally made these themes. I didn't realize the repo and homepage links were going to be on the side and easily overlooked like they are. 

If I were to add something to the readme, what would you feel would be most helpful?

**Comment by bbenoist** [comment]
> If I were to add something to the readme, what would you feel would be most helpful?

On the extensions I personally develop, I've added a dedicated section. [Here is an example](https://github.com/bbenoist/vscode-shell#issues--feature-requests).

I also added a badge with issue count but it looks like shields.io is not reliable as images regularly end-up not being displayed :cry:

**Comment by gerane** [comment]
I am adding icons and screenshots to my themes currently, and adding an easier to find links in the readme files as you suggested.

**Comment by gerane** [comment]
I added icons and screenshots to all of my themes and also added links to github
