### ISSUE TITLE
Birds of Paradise Stopped Working

### ISSUE THREAD

**Issue by LoganBresnahan** [gerane/VSCodeThemes#66]
Birds of Paradise version 0.0.3 stopped working for me. VSCode does not recognize "BirdsofParadise" in the settings.json file. It also does not show in the Color Theme Preferences. Installing 0.0.2 fixes the issue for me.

VSCode 1.39.1
Fedora x64

Thanks for your work.

**Comment by DeoThemes** [comment]
Same for Flat theme. After VSC update, the theme is not recognized.

**Comment by vluoto** [comment]
Same for Chelevra after update. :–(

**Comment by Enrika** [comment]
And Easyballs as well.  My eyeballs are indeed uneasy now.  I'll go back to the previous version of VS Code before I'll give up my Easyballs.

**Comment by evritt** [comment]
Eiffel no longer works either. I am guessing all the themes are borked at the moment.

**Comment by BlueBlazin** [comment]
Same for brogrammer.
