### ISSUE TITLE
VSCode 1.39.1 Dracula Theme not work

### ISSUE THREAD

**Issue by jundge** [gerane/VSCodeThemes#67]
At the latest vsocode version (1.39.1) in the morning ,it stopped work

**Comment by mardesnic** [comment]
Same with Sunburst Theme, not working since new update.

**Comment by Seerdon** [comment]
aaaaa, Sunburst is not working :(

**Comment by JohnPiepersSmits** [comment]
I have it working again, see my issue that I opened.
