### ISSUE TITLE
Sunburst Theme not selectable

### ISSUE THREAD

**Issue by JohnPiepersSmits** [gerane/VSCodeThemes#68]
Since the last update the sunburst theme can not be selected any more.
After some debugging I noticed errors in the package.json (in the extension folder) at lines:
"name": "theme-sunburst",  -> was in uppercase
and I changed in contribute.themes the object to:
"themes": [
			{
				"label": "Sunburst",
				"uiTheme": "vs-dark",
				"path": "./themes/Sunburst.tmTheme"
			}
		]

After this, I could select this theme again!
This might work for other themes too.

**Comment by Seerdon** [comment]
Where is it exacly?

**Comment by Seerdon** [comment]
OK, I have it, for windows it is in Users/{login}/.vscode folder. 
Thanks it is working now. 
Sunburst is the best theme for coding.

**Comment by JohnPiepersSmits** [comment]
I agree with you! 
And yes, it was in that folder...

**Comment by williamengbjerg** [comment]
Works! Thx.
