### ISSUE TITLE
HalfLife Theme Doesn't Work Anymore

### ISSUE THREAD

**Issue by eiskalteschatten** [gerane/VSCodeThemes#69]
I've used the HalfLife theme for a long time, but since updating to Visual Studio Code 1.39.2 today, it no longer works. I can't select it or change to it. I've uninstalled it, reinstalled it, disabled it and re-enabled it with no luck.

This error appears in the Visual Studio Code dev tools console:

```
[gerane.Theme-HalfLife]: Expected string in `contributes.themes.path`. Provided value: undefined
```

I'm running Visual Studio Code on macOS 10.15 (Catalina).

**Comment by jundge** [comment]
I only found setting.json.Where is package.json?

**Comment by Niels-NTG** [comment]
@jundge If you open your VSC command palette and run "Open extensions folder" and then find a folder named `gerane.theme-${your-fav-theme}` you will find the `package.json` file there.
