### ISSUE TITLE
Twilight no longer listed after update

### ISSUE THREAD

**Issue by rbx** [gerane/VSCodeThemes#71]
After updating the theme, it is no longer active and is not listed in the theme list:

![Screenshot_2019-10-16_10-49-12](https://user-images.githubusercontent.com/1915061/66903421-bc398d80-f002-11e9-8b46-cf1ed896e86e.png)

VSCode:
```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.0-31-generic
```
Extension:
```
Name: Twilight Theme
Id: gerane.theme-twilight
Description: Twilight Theme ported from the Twilight TextMate Theme
Version: 0.0.4
Publisher: gerane
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=gerane.Theme-Twilight
```

**Comment by evenfrost** [comment]
Same for me. Using https://marketplace.visualstudio.com/items?itemName=NikosKornarakis.predawn-twilight in the meanwhile.

**Comment by jaysalvat** [comment]
+1
