### ISSUE TITLE
Brogrammer theme doesn't work on lates VS Code update

### ISSUE THREAD

**Issue by ArturoEsqCR** [gerane/VSCodeThemes#75]
Brogrammer theme doesn't show up on color theme list

**Comment by ManuLEM** [comment]
Found a way to fix here [https://github.com/gerane/VSCodeThemes/issues/68#issue-507675883](https://github.com/gerane/VSCodeThemes/issues/68#issue-507675883)
Basically, in the package.json of the theme (in `~/.vscode/extensions/gerane.theme-brogrammer-0.1.2/`), you need to convert the contributes.themes value to : 
`[
			{
				"label": "Brogrammer" ,
				"uiTheme": "vs-dark",
				"path": "./themes/Brogrammer.tmTheme"
			}
		]`
